name: DarthCraft
version: 2.1.1
description: Custom plugin for DarthCraft
softdepend: [Votifier]
authors: [DarthSalamon, Wild1145]
main: net.darthcraft.dcmod.DarthCraft
commands:
  ban:
    description: Bans a player
    usage: /<command> <player> <reason>
  banip:
    description: Bans the last Ip of a player (or all)
    usage: /<command> [-a] <player> <reason>
  unban:
    description: Unbans a player and all attached IPs
    usage: /<command> <player>
  o:
    description: Says a message in AdminChat
    usage: /<command> [message]
  setrank:
    description: Sets (forcefully) the rank of a player
    usage: /<command> [-f] <player> <guest|member|loyal|admin|pradmin|headadmin|host>
  trollmode:
    description: Trololol
    usage: /<command> <on|off>
  mute:
    description: Mutes a player
    usage: /<command> <player>
  unmute:
    description: Unmutes a player
    usage: /<command> <player>
  kick:
    description: Kicks a player
    usage: /<command> <player> <reason>
  tempban:
    description: Temporarily bans a player
    usage: /<command> <player> <timeoffset> <reason>
  darthcraft:
    description: Shows information about DarthCraft, the plugin that runs it or reloads the config.
    usage: /<command> [<plugin | reload>]
    aliases: [dc]
  like:
    description: Like DarthCraft!
    usage: /<command> [<amount | set | remove>]
  busy:
    description: Toggles busy status
    usage: /<command>
  topic:
    description: Generates a random topic of discussion from the configuration file
    usage: /<command>
  warn:
    description: Warns a player and issues appropriate infraction points
    usage: /<command> <player> <amount> <reason>
  invade:
    description: A pointless command to mess with Jake
    usage: /<command> <player>